package schooldiary.enums;

public enum Lesson { READING, WORK, NATURE, MATHS, MUSIC, DRAWING, RUSSIAN, PD, FOREIGN_LANGUAGE,
    HISTORY, LITERATURE, OBJ, GEOGRAPHY, BIOLOGY, COMPUTER_SCIENCE, MECHANICAL_DRAWING, ALGEBRA, GEOMETRY,
    PHYSICS, CHEMISTRY, ASTRONOMY;

    Lesson() {
    }
}
